apiVersion: batch/v1
kind: Job
metadata:
  name: database-migration-job
  namespace: default
spec:
  template:
    spec:
      imagePullSecrets:           
        - name: ghcr-secret
      containers:
        - name: migration-engine
          image: ghcr.io/ishehov-devops-practice/db-migrations:latest
          args:
            - "-database"
            - "$(DATABASE_URL)"
            - "up"
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db-url
            
      restartPolicy: OnFailure
  backoffLimit: 4