networks:
  public-network:
    driver: bridge
  private-network:
    driver: bridge

services:
  gateway:
    image: nginx:alpine
    container_name: network-gateway
    ports:
      - "80:80"
    networks:
      - public-network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      frontend-react:
        condition: service_started
      api-node:
        condition: service_started
      api-golang:
        condition: service_started
  postgres-db:
    image: postgres:16-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - private-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  db-migrations:
    image: ghcr.io/ishehov-devops-practice/db-migrations:latest
    container_name: db-migrations
    networks:
      - private-network
    depends_on:
      postgres-db:
        condition: service_healthy
    command: ["-database", "postgresql://${DB_USER}:${DB_PASSWORD}@postgres-db:5432/${DB_NAME}?sslmode=disable", "up"]

  api-node:
    image: ghcr.io/ishehov-devops-practice/api-node:latest
    container_name: api-node
    networks:
      - private-network
      - public-network
    environment:
      - DB_HOST=postgres-db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=5432
      - PORT=3000
    depends_on:
      db-migrations:
        condition: service_completed_successfully

  api-golang:
    image: ghcr.io/ishehov-devops-practice/api-golang:latest
    container_name: api-golang
    networks:
      - private-network
      - public-network
    environment:
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@postgres-db:5432/${DB_NAME}?sslmode=disable
    depends_on:
      db-migrations:
        condition: service_completed_successfully

  frontend-react:
    image: ghcr.io/ishehov-devops-practice/frontend-react:latest
    container_name: frontend-react
    networks:
      - public-network
    depends_on:
      api-node:
        condition: service_started
      api-golang:
        condition: service_started