version: '3.8'

networks:
  sandbox-mesh:
    driver: bridge

services:
  postgres-db:
    image: postgres:16-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    networks:
      - sandbox-mesh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  db-migrations:
    # Looks for the db-migrations code directory sitting parallel to devops-infra
    build: ../db-migrations
    container_name: db-migrations
    networks:
      - sandbox-mesh
    depends_on:
      postgres-db:
        condition: service_healthy
    command: ["-database", "postgresql://${DB_USER}:${DB_PASSWORD}@postgres-db:5432/${DB_NAME}?sslmode=disable", "up"]