---
- name: Fetch K3s config
  hosts: master
  become: true

  tasks:
    - name: Read k3s config
      slurp:
        src: /etc/rancher/k3s/k3s.yaml
      register: kubeconfig_encoded

    - name: Write k3s config locally
      delegate_to: localhost
      become: false
      copy:
        content: "{{ kubeconfig_encoded.content | b64decode | replace('127.0.0.1', hostvars['k3s-master-01']['ansible_host']) }}"
        dest: "{{ lookup('env', 'HOME') }}/Dev/.kube/config-proxmox-k3s"
        mode: '0600'